import os
import argparse
from .core.bridge import BridgeCore

# @intent:responsibility コマンドライン引数の処理、 .gitignore の自動生成、 
#                         および BridgeCore の起動（ブートストラップ）を担当するエントリーポイント。

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", action="version", version="CIP-Bridge v3.0.0 (Refactored)")
    parser.parse_args()

    ignore_file = ".gitignore"
    entries = { "cip_bus/", "bridge_events.log", "*.pid", "*.log", "__pycache__/" }
    current_content = set()
    if os.path.exists(ignore_file):
        with open(ignore_file, "r") as f:
            current_content = set(line.strip() for line in f if line.strip() and not line.startswith("#"))
    missing = entries - current_content
    if missing:
        try:
            with open(ignore_file, "a") as f:
                if os.path.exists(ignore_file) and os.path.getsize(ignore_file) > 0:
                     with open(ignore_file, "rb") as f_rb:
                         f_rb.seek(-1, 2)
                         if f_rb.read(1) != b"\n": f.write("\n")
                f.write("\n# Auto-generated by CIP-Bridge\n")
                for entry in missing: f.write(f"{entry}\n")
        except Exception: pass

    bridge = BridgeCore()
    bridge.run()

if __name__ == "__main__":
    main()